### ISSUE TITLE
This does not use Om!

### ISSUE THREAD

**Issue by brentvatne** [landau/cljs-pomodoro#13]
It looks like [you rewrote this](https://github.com/landau/cljs-pomodoro/commit/a00c70ca61642f45862e7be5d4223298042cc053) to use Reagent rather than Om - README and project description should be updated. Thanks for the code, either way!

**Comment by landau** [comment]
This is true. [insert excuse for lazy here] :)

**Comment by landau** [comment]
feel free to PR over my laziness
