### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by landau** [landau/cljs-pomodoro#8]
clean up code from learnings

**Comment by cpdean** [comment]
What motivated the rewrite?  I've been trying to learn Om, but the fact your reagent rewrite looks way cleaner has me reconsidering.

**Comment by landau** [comment]
Honestly, the cleaner refactor has to do with me understanding clojure. Om is still a good solution, but this project is mostly to play around with different technologies. However, I've always been a fan of flexibility and Reagent is certainly simpler. I always like how it uses hiccup style templates.

I say give them both a shot on a simple app. I don't think this application provides a good idea of what a larger application might require (if thats what you need).
